runtime: python27
api_version: 1
threadsafe: true

handlers:
  - url: /(.+).(css|html|js|json|png|svg|ico)
    static_files: dist/Reel-Fish-Co/\1.\2
    upload: dist/Reel-Fish-Co/.*

  - url: /(.*)
    static_files: dist/Reel-Fish-Co/index.html
    upload: dist/Reel-Fish-Co/index.html

# Skip any files not in the dist folder
skip_files:
  - (?!^dist|docs)
